#!/usr/bin/env python

import sys
import re
import csv

if len(sys.argv) < 3:
	print 'Usage: hp inputfile outputfile\n\nwhere inputfile is the result of heroku -p router'
	exit()
	
f = open(sys.argv[1], 'r')

freq = dict()

for line in f:
	speed = int(re.findall('service=([0-9]+)ms', line)[0])
	if speed in freq:
		freq[speed] += 1
	else:
		freq[speed] = 1

fieldnames = ['ms', 'freq']

dw = csv.DictWriter(open(sys.argv[2], 'w'), delimiter=',', fieldnames=fieldnames)

dw.writer.writerow(fieldnames)

for item in sorted(freq.iteritems()):
    dw.writer.writerow(item)
